### PR TITLE
Use composer install to install the package

### PR DESCRIPTION
**Pull request by freekmurze**
This is an easier way to install that package than editing the composer.json. It'll also always pull in the latest stable version.

### CODE REVIEW

**Comment by vinkla** [comment]
+1 This is definitely much better and easier to do!

**Comment by freekmurze** [comment]
Fixed the composer command, sorry about that.

**Comment by vinkla** [comment]
:+1:

**Comment by maxiloc** [comment]
@freekmurze I not against adding the composer require way to install but I will let at least :
\---
You can also add ```algolia/algoliasearch-client-php": "1.5.* ``` to your ```composer.json```
\---
because for me it's good to have the current major version in the doc.

What do you think ?

**Comment by freekmurze** [comment]
I don't think it's necessary.  New users should always require the latest stable version of the package. `composer require` does that for you.

(isn't the latest current version 1.6?)

**Comment by maxiloc** [comment]
@freekmurze Yes your are right we are at 1.6
It will avoid having to maintain the version number there

**Comment by redox** [comment]
@maxiloc Don't forget to apply the change in https://github.com/algolia/algoliasearch-client-readme-generator/blob/master/include/PHP/setup.snippet, otherwise we'll lose the update the next time we rebuild our READMEs.

**Comment by maxiloc** [comment]
@redox thanks will do

**Pull request merged**
