### PR TITLE
fix: add PHP 8.1 compatibility

### LINKED ISSUE #694: PHP 8.1 AbstractResponse offset methods deprecation
Under PHP 8.1 we're getting errors such as:

> Deprecated: Return type of Algolia\AlgoliaSearch\Response\AbstractResponse::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in

Fix is simple - just adding return types, but it would break backward compatibility - perhaps a candidate for the next major release?

### PR DESCRIPTION
**Pull request by damcou**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| Related Issue     | Fix #694

### CODE REVIEW

**Comment by DevinCodes** [comment]
This looks good, thank you! Can you just add PHP 8.1 to the testing matrix in `.circleci/config.yml`, please?

**Comment by damcou** [comment]
> This looks good, thank you! Can you just add PHP 8.1 to the testing matrix in `.circleci/config.yml`, please?

I'll add it once the image is available; are you ok to merge this PR in the meantime ?

**Review by DevinCodes — APPROVED** [review]

**Comment by greg0ire** [comment]
@damcou @DevinCodes can we please get a new release including this fix? Right now, we get lots of deprecation warnings.

**Comment by damcou** [comment]
Hello @greg0ire , we should release the new version early next week, sorry for the delay.

**Comment by greg0ire** [comment]
That's awesome news! Looking forward to that :slightly_smiling_face:

**Pull request merged**
